language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "pypy3"
env:
  - GALLERYDL_TESTS=core
matrix:
  include:
    - python: "3.8"
      env: GALLERYDL_TESTS=results
    - language: minimal
      env: GALLERYDL_TESTS=snap
      addons:
        snaps:
          - name: snapcraft
            classic: true
      install:
        - true
      script:
        - sudo apt update
        - snapcraft --destructive-mode
        - sudo snap try
        - snap run gallery-dl --verbose https://twitter.com/ubuntu/status/1121001597092364288

git:
  depth: 3
  quiet: true
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(-\S*)?$/
  - /^test(-\w+)+$/
script:
  - ./scripts/run_tests.sh
