sudo: false
language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements.txt
script:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.3' ]]; then nosetests --ignore-files=test_extractors --verbose test; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then nosetests --verbose test; fi
