sudo: false
language: python
python:
  - 3.3
  - 3.4
  - 3.5
  - 3.6
install:
  - pip install -r requirements.txt
script:
  - if [[ $TRAVIS_PYTHON_VERSION != '3.6' ]]; then nosetests --ignore-files=test_extractors --verbose test; fi
  - if [[ $TRAVIS_PYTHON_VERSION == '3.6' ]]; then nosetests --verbose test; fi
git:
  depth: 10
