language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
env:
  - GALLERYDL_TESTS=core
matrix:
  include:
    - python: "3.6"
      env: GALLERYDL_TESTS=results

sudo: false
git:
  depth: 3
branches:
  only:
  - master
  - /^v\d+\.\d+\.\d+(-\S*)?$/

script:
  - ./scripts/run_tests.sh
